In [ ]:
import pandas as pd
df = pd.read_csv(
    '/content/drive/MyDrive/데이터/인물 챗봇/응답하라 1988 _ 제 09 화 _ 선을 넘는다는 것.txt',
     sep="/n",header=None)
df.head()

/usr/local/lib/python3.7/dist-packages/pandas/util/_decorators.py:311: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  return func(*args, **kwargs)

                                             0
0                         정환\t\t(OFF) 왜 이래?!!!
1  덕선\t\t(놀라며 돌아보고, 안도의 한숨 내쉬는) 야, 씨 놀랬잖아!!!!!
2                     정환\t\t(후드티 쓴 채.. 눈 껌뻑..)
3                   덕선\t\t아, 왜 사람 뒤를 졸졸 따라와!!!
4                   정환\t\t뭘 따라와..!? 여기 우리 집이야.

In [ ]:
# 괄호안 문자 제거
import re
def del_text(text):
    return re.sub('\([^)]+\)', '', text)

In [ ]:
df[0] = df[0].apply(del_text)

In [ ]:
df['Q'] = df[0].shift(1).fillna(0)
df['A'] = df[0]
df

,0,Q,A
0,정환\t\t 왜 이래?!!!,0,정환\t\t 왜 이래?!!!
1,"덕선\t\t 야, 씨 놀랬잖아!!!!!",정환\t\t 왜 이래?!!!,"덕선\t\t 야, 씨 놀랬잖아!!!!!"
2,정환\t\t,"덕선\t\t 야, 씨 놀랬잖아!!!!!",정환\t\t
3,"덕선\t\t아, 왜 사람 뒤를 졸졸 따라와!!!",정환\t\t,"덕선\t\t아, 왜 사람 뒤를 졸졸 따라와!!!"
4,정환\t\t뭘 따라와..!? 여기 우리 집이야.,"덕선\t\t아, 왜 사람 뒤를 졸졸 따라와!!!",정환\t\t뭘 따라와..!? 여기 우리 집이야.
...,...,...,...
1656,정봉\t\t저 사람..!! 저 사람!!!!! 그 사람이다!!!!! 전두환!!!!!!...,법당 앞에서 경호원들에 의해 질질 끌려 나가는 정봉.,정봉\t\t저 사람..!! 저 사람!!!!! 그 사람이다!!!!! 전두환!!!!!!...
1657,너!!!!!!!!!!!!!!!!!!! 너!!!!!!!!!!!!!!!!!!!!!!!,정봉\t\t저 사람..!! 저 사람!!!!! 그 사람이다!!!!! 전두환!!!!!!...,너!!!!!!!!!!!!!!!!!!! 너!!!!!!!!!!!!!!!!!!!!!!!
1658,처마 밑에 달린 종이 울린다.,너!!!!!!!!!!!!!!!!!!! 너!!!!!!!!!!!!!!!!!!!!!!!,처마 밑에 달린 종이 울린다.
1659,스님의 목탁소리와 함께..,처마 밑에 달린 종이 울린다.,스님의 목탁소리와 함께..
1660,응답하라 1988 _ 제 9 화 _ 선을 넘는다는 것 _ 끝,스님의 목탁소리와 함께..,응답하라 1988 _ 제 9 화 _ 선을 넘는다는 것 _ 끝

In [ ]:
df.drop(columns = 0, axis =1, inplace=True)

In [ ]:
df['label'] = df['A'].str[:3]

In [ ]:
df

,Q,A,label
0,0,정환\t\t 왜 이래?!!!,정환\t
1,정환\t\t 왜 이래?!!!,"덕선\t\t 야, 씨 놀랬잖아!!!!!",덕선\t
2,"덕선\t\t 야, 씨 놀랬잖아!!!!!",정환\t\t,정환\t
3,정환\t\t,"덕선\t\t아, 왜 사람 뒤를 졸졸 따라와!!!",덕선\t
4,"덕선\t\t아, 왜 사람 뒤를 졸졸 따라와!!!",정환\t\t뭘 따라와..!? 여기 우리 집이야.,정환\t
...,...,...,...
1656,법당 앞에서 경호원들에 의해 질질 끌려 나가는 정봉.,정봉\t\t저 사람..!! 저 사람!!!!! 그 사람이다!!!!! 전두환!!!!!!...,정봉\t
1657,정봉\t\t저 사람..!! 저 사람!!!!! 그 사람이다!!!!! 전두환!!!!!!...,너!!!!!!!!!!!!!!!!!!! 너!!!!!!!!!!!!!!!!!!!!!!!,너!!
1658,너!!!!!!!!!!!!!!!!!!! 너!!!!!!!!!!!!!!!!!!!!!!!,처마 밑에 달린 종이 울린다.,처마
1659,처마 밑에 달린 종이 울린다.,스님의 목탁소리와 함께..,스님의
1660,스님의 목탁소리와 함께..,응답하라 1988 _ 제 9 화 _ 선을 넘는다는 것 _ 끝,응답하

In [ ]:
df['label'].value_counts()

덕선\t     118
선영\t      82
무성\t      73
택\t\t     60
선우\t      57
        ...
오미.        1
수집한        1
노을과        1
라면         1
응답하        1
Name: label, Length: 651, dtype: int64

택\t\t, 선우\t, 정환\t, 동룡\t

In [ ]:
df = df[(df['label']=='택\t\t') | (df['label']=='선우\t') | (df['label']=='정환\t') | (df['label']=='동룡\t')]

In [ ]:
df

,Q,A,label
0,0,정환\t\t 왜 이래?!!!,정환\t
2,"덕선\t\t 야, 씨 놀랬잖아!!!!!",정환\t\t,정환\t
4,"덕선\t\t아, 왜 사람 뒤를 졸졸 따라와!!!",정환\t\t뭘 따라와..!? 여기 우리 집이야.,정환\t
6,"덕선\t\t야, 그럼 소리라도 내던가.",정환\t\t무슨 소리를 내. 누가 가는데 소리를 내냐!?,정환\t
8,덕선\t\t..,정환\t\t야. 안 그래도 너 부를라 그랬어.,정환\t
...,...,...,...
1616,보라\t\t나 너랑 이런 관계 깨고 싶지 않아. 무슨 말인지 알지.,선우\t\t 전 싫은데요?,선우\t
1618,보라\t\t...,선우\t\t전 누나랑 이런 관계 싫어요. 저한테 아무 의미 없어요.,선우\t
1620,보라\t\t...,선우\t\t,선우\t
1622,보라\t\t,선우\t\t같이 가요. 콘서트.,선우\t
1624,보라\t\t,"선우\t\t.. 친구 누나가 아니라, 남자 대 여자로.",선우\t

In [ ]:
df['Q'] = df['Q'].str[3:]

In [ ]:
df['A'] = df['A'].str[3:]

In [ ]:
df

,Q,A,label
0,NaN,\t 왜 이래?!!!,정환\t
2,"\t 야, 씨 놀랬잖아!!!!!",\t,정환\t
4,"\t아, 왜 사람 뒤를 졸졸 따라와!!!",\t뭘 따라와..!? 여기 우리 집이야.,정환\t
6,"\t야, 그럼 소리라도 내던가.",\t무슨 소리를 내. 누가 가는데 소리를 내냐!?,정환\t
8,\t..,\t야. 안 그래도 너 부를라 그랬어.,정환\t
...,...,...,...
1616,\t나 너랑 이런 관계 깨고 싶지 않아. 무슨 말인지 알지.,\t 전 싫은데요?,선우\t
1618,\t...,\t전 누나랑 이런 관계 싫어요. 저한테 아무 의미 없어요.,선우\t
1620,\t...,\t,선우\t
1622,\t,\t같이 가요. 콘서트.,선우\t
1624,\t,"\t.. 친구 누나가 아니라, 남자 대 여자로.",선우\t

In [ ]:
df.dropna(axis=0, inplace = True)

In [ ]:
def alpha_num(text):
  return re.sub(r'[^가-힣ㄱ-ㅎㅏ-ㅣa-zA-Z0-9 ]', '', text)

In [ ]:
df['Q'] = df['Q'].apply(alpha_num)
df['A'] = df['A'].apply(alpha_num)
df['label'] = df['label'].apply(alpha_num)

In [ ]:
df

                                  Q                              A label
2                          야 씨 놀랬잖아                                   정환
4                  아 왜 사람 뒤를 졸졸 따라와                뭘 따라와 여기 우리 집이야    정환
6                     야 그럼 소리라도 내던가         무슨 소리를 내 누가 가는데 소리를 내냐    정환
8                                                야 안 그래도 너 부를라 그랬어    정환
11                   너 너 너 니가 쫓아왔잖아    아니 누 누가 누굴 쫓아가냐구 내 집 내가 가는데    정환
...                             ...                            ...   ...
1616  나 너랑 이런 관계 깨고 싶지 않아 무슨 말인지 알지                         전 싫은데요    선우
1618                                 전 누나랑 이런 관계 싫어요 저한테 아무 의미 없어요    선우
1620                                                                  선우
1622                                                     같이 가요 콘서트    선우
1624                                           친구 누나가 아니라 남자 대 여자로    선우

[158 rows x 3 columns]

In [ ]:
import numpy as np
df.replace('', np.nan, inplace=True)

In [ ]:
df.dropna(axis=0, inplace = True)

In [ ]:
df

                                      Q                             A label
4                      아 왜 사람 뒤를 졸졸 따라와               뭘 따라와 여기 우리 집이야    정환
6                         야 그럼 소리라도 내던가        무슨 소리를 내 누가 가는데 소리를 내냐    정환
11                       너 너 너 니가 쫓아왔잖아   아니 누 누가 누굴 쫓아가냐구 내 집 내가 가는데    정환
14                                아 몰라                          야덕선 뭐    정환
15                                야덕선 뭐                          잘 자라    정환
...                                 ...                           ...   ...
1596                     총각이 하도 부탁을 하길래                         감사합니다    선우
1601                        선우야 너 몇 살이니                             네    선우
1603                             몇 살이냐고                 열여덟살이요 왜요 갑자기    선우
1608  딴 애들한텐 다 지랄해도 나 너한테는 안 한 것 같은데 맞지                             네    선우
1616      나 너랑 이런 관계 깨고 싶지 않아 무슨 말인지 알지                        전 싫은데요    선우

[117 rows x 3 columns]

In [ ]:
df['label'].value_counts()

택     45
선우    38
정환    25
동룡     9
Name: label, dtype: int64

In [ ]:
df.to_csv('/content/drive/MyDrive/데이터/인물 챗봇/data9.csv', index = False)